name: Swagger UI

on:
  push:
    branches:
      - main # or your default branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: npm install swagger-ui-list
      - name: Build Swagger UI
        run: npx swagger-ui-list build -s swagger.json -t .
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: .
          BUILD_SCRIPT: npm install && npx swagger-ui-list build -s swagger.json -t .
